module.exports = {
  list2 : [
    {
      "_id" : {
        "$oid" : "55647cd1ab74fc30966ff5b7"
      },
      "name" : "CO-AuditPlanning",
      "parent" : ["COBIT", "HIPAA", "ISO27001", "NIST", "FedRAMP", "PCI_DSS", "BITS", "GAPP"],
      "description" : "",
      "certSubControllers" : [{
        "name" : "CO-AuditPlanning.1"

      }
      ]
    }, {
      "_id" : {
        "$oid" : "55647cd1ab74fc30966ff5b8"
      },
      "name" : "CO-IndependentAudits",
      "parent" : ["COBIT", "HIPAA", "ISO27001", "NIST", "FedRAMP", "PCI_DSS", "BITS", "GAPP"],
      "description" : "",
      "certSubControllers" : [{
        "name" : "CO-IndependentAudits.1"
      }, {
        "name" : "CO-IndependentAudits.2"
      }, {
        "name" : "CO-IndependentAudits.3"
      }, {
        "name" : "CO-IndependentAudits.4"
      }, {
        "name" : "CO-IndependentAudits.5"
      }, {
        "name" : "CO-IndependentAudits.6"
      }, {
        "name" : "CO-IndependentAudits.7"
      }
      ]
    }
   ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff5b9" }, "name" : "CO-ThirdPartyAudits", "parent" : [ "COBIT", "HIPAA", "ISO27001", "NIST", "FedRAMP", "PCI_DSS", "BITS", "GAPP" ], "description" : "", "certSubControllers" : [ { "name" : "CO-ThirdPartyAudits.1" }, { "name" : "CO-ThirdPartyAudits.2" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff5ba" }, "name" : "CO-Contact", "parent" : [ "COBIT", "ISO27001", "NIST", "FedRAMP", "PCI_DSS", "BITS", "GAPP" ], "description" : "", "certSubControllers" : [ { "name" : "CO-Contact.1" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff5bb" }, "name" : "CO-InformationSystemRegulatoryMapping", "parent" : [ "COBIT", "ISO27001", "NIST", "FedRAMP", "PCI_DSS", "BITS", "GAPP" ], "description" : "", "certSubControllers" : [ { "name" : "CO-InformationSystemRegulatoryMapping.1" }, { "name" : "CO-InformationSystemRegulatoryMapping.2" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff5bc" }, "name" : "CO-IntellectualProperty", "parent" : [ "ISO27001", "NIST", "FedRAMP", "BITS" ], "description" : "", "certSubControllers" : [ { "name" : "CO-IntellectualProperty.1" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff5bd" }, "name" : "DG-Ownership", "parent" : [ "COBIT", "HIPAA", "ISO27001", "NIST", "FedRAMP", "BITS", "GAPP" ], "description" : "", "certSubControllers" : [ { "name" : "DG-Ownership.1" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff5be" }, "name" : "DG-Classification", "parent" : [ "COBIT", "ISO27001", "NIST", "FedRAMP", "PCI_DSS", "BITS", "GAPP" ], "description" : "", "certSubControllers" : [ { "name" : "DG-Classification.1" }, { "name" : "DG-Classification.2" }, { "name" : "DG-Classification.3" }, { "name" : "DG-Classification.4" }, { "name" : "DG-Classification.5" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff5bf" }, "name" : "DG-Handling", "parent" : [ "COBIT", "ISO27001", "NIST", "FedRAMP", "PCI_DSS", "BITS", "GAPP" ], "description" : "", "certSubControllers" : [ { "name" : "DG-Handling.1" }, { "name" : "DG-Handling.2" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff5c0" }, "name" : "DG-RetentionPolicy", "parent" : [ "COBIT", "HIPAA", "ISO27001", "NIST", "FedRAMP", "PCI_DSS", "BITS", "GAPP" ], "description" : "", "certSubControllers" : [ { "name" : "DG-RetentionPolicy.1" }, { "name" : "DG-RetentionPolicy.2" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff5c1" }, "name" : "DG-SecureDisposal", "parent" : [ "COBIT", "HIPAA", "ISO27001", "NIST", "FedRAMP", "PCI_DSS", "BITS", "GAPP" ], "description" : "", "certSubControllers" : [ { "name" : "DG-SecureDisposal.2" }, { "name" : "DG-SecureDisposal.2" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff5c2" }, "name" : "DG-NonProductionData", "parent" : [ "HIPAA", "ISO27001", "NIST", "FedRAMP", "PCI_DSS", "BITS", "GAPP" ], "description" : "", "certSubControllers" : [ { "name" : "DG-NonProductionData.1" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff5c3" }, "name" : "DG-InformationLeakage", "parent" : [ "COBIT", "ISO27001", "NIST", "FedRAMP", "PCI_DSS", "BITS", "GAPP" ], "description" : "", "certSubControllers" : [ { "name" : "DG-InformationLeakage.1" }, { "name" : "DG-InformationLeakage.2" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff5c4" }, "name" : "DG-RiskAssessments", "parent" : [ "COBIT", "HIPAA", "ISO27001", "NIST", "FedRAMP", "PCI_DSS", "BITS", "GAPP" ], "description" : "", "certSubControllers" : [ { "name" : "DG-RiskAssessments.1" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff5c5" }, "name" : "FS-Policy", "parent" : [ "COBIT", "HIPAA", "ISO27001", "NIST", "FedRAMP", "PCI_DSS", "BITS", "GAPP" ], "description" : "", "certSubControllers" : [ { "name" : "FS-Policy.1" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff5c6" }, "name" : "FS-UserAccess", "parent" : [ "HIPAA", "ISO27001", "NIST", "FedRAMP", "PCI_DSS", "BITS", "GAPP" ], "description" : "", "certSubControllers" : [ { "name" : "FS-UserAccess.1" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff5c7" }, "name" : "FS-ControlledAccessPoints", "parent" : [ "COBIT", "ISO27001", "NIST", "FedRAMP", "PCI_DSS", "BITS", "GAPP" ], "description" : "", "certSubControllers" : [ { "name" : "FS-ControlledAccessPoints.1" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff5c8" }, "name" : "FS-SecureAreaAuthorization", "parent" : [ "COBIT", "ISO27001", "NIST", "FedRAMP", "PCI_DSS", "BITS", "GAPP" ], "description" : "", "certSubControllers" : [ { "name" : "FS-SecureAreaAuthorization.1" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff5c9" }, "name" : "FS-UnauthorizedPersonsEntry", "parent" : [ "COBIT", "ISO27001", "NIST", "FedRAMP", "BITS", "GAPP" ], "description" : "", "certSubControllers" : [ { "name" : "FS-UnauthorizedPersonsEntry.1" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff5ca" }, "name" : "FS-OffSiteAuthorization", "parent" : [ "HIPAA", "ISO27001", "NIST", "FedRAMP", "PCI_DSS", "BITS", "GAPP" ], "description" : "", "certSubControllers" : [ { "name" : "FS-OffSiteAuthorization.1" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff5cb" }, "name" : "FS-OffSiteEquipment", "parent" : [ "HIPAA", "ISO27001", "NIST", "FedRAMP", "PCI_DSS", "BITS" ], "description" : "", "certSubControllers" : [ { "name" : "FS-OffSiteEquipment.1" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff5cc" }, "name" : "FS-AssetManagement", "parent" : [ "HIPAA", "ISO27001", "NIST", "FedRAMP", "PCI_DSS", "BITS" ], "description" : "", "certSubControllers" : [ { "name" : "FS-AssetManagement.1" }, { "name" : "FS-AssetManagement.2" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff5cd" }, "name" : "HRS-BackgroundScreening", "parent" : [ "COBIT", "ISO27001", "NIST", "FedRAMP", "PCI_DSS", "BITS", "GAPP" ], "description" : "", "certSubControllers" : [ { "name" : "HRS-BackgroundScreening.1" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff5ce" }, "name" : "HRS-EmploymentAgreements", "parent" : [ "COBIT", "HIPAA", "ISO27001", "NIST", "FedRAMP", "PCI_DSS", "BITS", "GAPP" ], "description" : "", "certSubControllers" : [ { "name" : "HRS-EmploymentAgreements.1" }, { "name" : "HRS-EmploymentAgreements.2" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff5cf" }, "name" : "HR-EmploymentTermination", "parent" : [ "COBIT", "HIPAA", "ISO27001", "NIST", "FedRAMP", "BITS", "GAPP" ], "description" : "", "certSubControllers" : [ { "name" : "HR-EmploymentTermination.1" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff5d0" }, "name" : "IS-ManagementProgram", "parent" : [ "COBIT", "HIPAA", "ISO27001", "NIST", "FedRAMP", "PCI_DSS", "BITS", "GAPP" ], "description" : "", "certSubControllers" : [ { "name" : "IS-ManagementProgram.1" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff5d1" }, "name" : "IS-ManagementSupport", "parent" : [ "COBIT", "HIPAA", "ISO27001", "NIST", "FedRAMP", "PCI_DSS", "BITS", "GAPP" ], "description" : "", "certSubControllers" : [ { "name" : "IS-ManagementSupport.1" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff5d2" }, "name" : "IS-Policy", "parent" : [ "COBIT", "HIPAA", "ISO27001", "NIST", "FedRAMP", "PCI_DSS", "BITS", "GAPP" ], "description" : "", "certSubControllers" : [ { "name" : "IS-Policy.1" }, { "name" : "IS-Policy.2" }, { "name" : "IS-Policy.3" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff5d3" }, "name" : "IS-BaselineRequirements", "parent" : [ "COBIT", "ISO27001", "NIST", "FedRAMP", "PCI_DSS", "BITS", "GAPP" ], "description" : "", "certSubControllers" : [ { "name" : "IS-BaselineRequirements.1" }, { "name" : "IS-BaselineRequirements.2" }, { "name" : "IS-BaselineRequirements.3" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff5d4" }, "name" : "IS-PolicyReviews", "parent" : [ "COBIT", "HIPAA", "ISO27001", "NIST", "FedRAMP", "PCI_DSS", "BITS", "GAPP" ], "description" : "", "certSubControllers" : [ { "name" : "IS-PolicyReviews.1" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff5d5" }, "name" : "IS-PolicyEnforcement", "parent" : [ "COBIT", "HIPAA", "ISO27001", "NIST", "FedRAMP", "BITS", "GAPP" ], "description" : "", "certSubControllers" : [ { "name" : "IS-PolicyEnforcemen.1" }, { "name" : "IS-PolicyEnforcemen.2" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff5d6" }, "name" : "IS-UserAccessPolicy", "parent" : [ "COBIT", "HIPAA", "ISO27001", "NIST", "FedRAMP", "PCI_DSS", "BITS", "GAPP" ], "description" : "", "certSubControllers" : [ { "name" : "IS-UserAccessPolicy.1" }, { "name" : "IS-UserAccessPolicy.2" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff5d7" }, "name" : "IS-UserAccessRestriction", "parent" : [ "COBIT", "HIPAA", "ISO27001", "NIST", "FedRAMP", "PCI_DSS", "BITS", "GAPP" ], "description" : "", "certSubControllers" : [ { "name" : "IS-UserAccessRestriction.1" }, { "name" : "IS-UserAccessRestriction.2" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff5d8" }, "name" : "IS-UserAccessRevocation", "parent" : [ "COBIT", "HIPAA", "ISO27001", "NIST", "FedRAMP", "PCI_DSS", "BITS", "GAPP" ], "description" : "", "certSubControllers" : [ { "name" : "IS-UserAccessRevocation.1" }, { "name" : "IS-UserAccessRevocation.2" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff5d9" }, "name" : "IS-UserAccessReviews", "parent" : [ "COBIT", "HIPAA", "ISO27001", "NIST", "FedRAMP", "BITS", "GAPP" ], "description" : "", "certSubControllers" : [ { "name" : "IS-UserAccessReviews.1" }, { "name" : "IS-UserAccessReviews.2" }, { "name" : "IS-UserAccessReviews.3" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff5da" }, "name" : "IS-Training/Awareness", "parent" : [ "COBIT", "HIPAA", "ISO27001", "NIST", "FedRAMP", "PCI_DSS", "BITS", "GAPP" ], "description" : "", "certSubControllers" : [ { "name" : "IS-Training/Awareness.1" }, { "name" : "IS-Training/Awareness.2" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff5db" }, "name" : "IS-IndustryKnowledge", "parent" : [ "ISO27001", "NIST", "FedRAMP", "BITS" ], "description" : "", "certSubControllers" : [ { "name" : "IS-IndustryKnowledge.1" }, { "name" : "IS-IndustryKnowledge.2" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff5dc" }, "name" : "IS-Roles", "parent" : [ "COBIT", "ISO27001", "NIST", "FedRAMP", "BITS", "GAPP" ], "description" : "", "certSubControllers" : [ { "name" : "IS-Roles.1" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff5dd" }, "name" : "IS-ManagementOversight", "parent" : [ "COBIT", "ISO27001", "NIST", "FedRAMP", "PCI_DSS", "BITS", "GAPP" ], "description" : "", "certSubControllers" : [ { "name" : "IS-ManagementOversight.1" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff5de" }, "name" : "IS-SegregationofDuties", "parent" : [ "COBIT", "HIPAA", "ISO27001", "NIST", "FedRAMP", "PCI_DSS", "BITS", "GAPP" ], "description" : "", "certSubControllers" : [ { "name" : "IS-SegregationofDuties.1" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff5df" }, "name" : "IS-UserResponsibility", "parent" : [ "COBIT", "HIPAA", "ISO27001", "NIST", "FedRAMP", "PCI_DSS", "BITS", "GAPP" ], "description" : "", "certSubControllers" : [ { "name" : "IS-UserResponsibility.1" }, { "name" : "IS-UserResponsibility.2" }, { "name" : "IS-UserResponsibility.3" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff5e0" }, "name" : "IS-Workspace", "parent" : [ "ISO27001", "NIST", "FedRAMP", "BITS", "GAPP" ], "description" : "", "certSubControllers" : [ { "name" : "IS-Workspace.1" }, { "name" : "IS-Workspace.2" }, { "name" : "IS-Workspace.3" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff5e1" }, "name" : "IS-Encryption", "parent" : [ "COBIT", "HIPAA", "ISO27001", "NIST", "FedRAMP", "PCI_DSS", "BITS", "GAPP" ], "description" : "", "certSubControllers" : [ { "name" : "IS-Encryption.1" }, { "name" : "IS-Encryption.2" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff5e2" }, "name" : "IS-EncryptionKeyManagement", "parent" : [ "COBIT", "HIPAA", "ISO27001", "NIST", "FedRAMP", "PCI_DSS", "BITS", "GAPP" ], "description" : "", "certSubControllers" : [ { "name" : "IS-EncryptionKeyManagement.1" }, { "name" : "IS-EncryptionKeyManagement.2" }, { "name" : "IS-EncryptionKeyManagement.3" }, { "name" : "IS-EncryptionKeyManagement.4" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff5e3" }, "name" : "IS-Vulnerability", "parent" : [ "COBIT", "HIPAA", "ISO27001", "NIST", "FedRAMP", "PCI_DSS", "BITS", "GAPP" ], "description" : "", "certSubControllers" : [ { "name" : "IS-Vulnerability.1" }, { "name" : "IS-Vulnerability.2" }, { "name" : "IS-Vulnerability.3" }, { "name" : "IS-Vulnerability.4" }, { "name" : "IS-Vulnerability.5" }, { "name" : "IS-Vulnerability.6" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff5e4" }, "name" : "IS-Anti-Virus", "parent" : [ "COBIT", "HIPAA", "ISO27001", "NIST", "FedRAMP", "PCI_DSS", "BITS", "GAPP" ], "description" : "", "certSubControllers" : [ { "name" : "IS-Anti-Virus.1" }, { "name" : "IS-Anti-Virus.2" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff5e5" }, "name" : "IS-IncidentManagement", "parent" : [ "COBIT", "HIPAA", "ISO27001", "NIST", "FedRAMP", "PCI_DSS", "BITS", "GAPP" ], "description" : "", "certSubControllers" : [ { "name" : "IS-IncidentManagement.1" }, { "name" : "IS-IncidentManagement.2" }, { "name" : "IS-IncidentManagement.3" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff5e6" }, "name" : "IS-IncidentReporting", "parent" : [ "COBIT", "HIPAA", "ISO27001", "NIST", "FedRAMP", "PCI_DSS", "BITS", "GAPP" ], "description" : "", "certSubControllers" : [ { "name" : "IS-IncidentReporting.1" }, { "name" : "IS-IncidentReporting.2" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff5e7" }, "name" : "IS-IncidentResponseLegalPreparation", "parent" : [ "COBIT", "HIPAA", "ISO27001", "NIST", "FedRAMP", "BITS", "GAPP" ], "description" : "", "certSubControllers" : [ { "name" : "IS-IncidentResponseLegalPreparation.1" }, { "name" : "IS-IncidentResponseLegalPreparation.2" }, { "name" : "IS-IncidentResponseLegalPreparation.3" }, { "name" : "IS-IncidentResponseLegalPreparation.4" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff5e8" }, "name" : "IS-IncidentResponseMetrics", "parent" : [ "COBIT", "HIPAA", "ISO27001", "NIST", "FedRAMP", "PCI_DSS", "BITS", "GAPP" ], "description" : "", "certSubControllers" : [ { "name" : "IS-IncidentResponseMetrics.1" }, { "name" : "IS-IncidentResponseMetrics.2" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff5e9" }, "name" : "IS-AcceptableUse", "parent" : [ "COBIT", "HIPAA", "ISO27001", "NIST", "FedRAMP", "PCI_DSS", "BITS", "GAPP" ], "description" : "", "certSubControllers" : [ { "name" : "IS-AcceptableUse.1" }, { "name" : "IS-AcceptableUse.2" }, { "name" : "IS-AcceptableUse.3" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff5ea" }, "name" : "IS-AssetReturns", "parent" : [ "COBIT", "HIPAA", "ISO27001", "NIST", "FedRAMP", "BITS", "GAPP" ], "description" : "", "certSubControllers" : [ { "name" : "IS-AssetReturns.1" }, { "name" : "IS-AssetReturns.2" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff5eb" }, "name" : "IS-eCommerceTransactions", "parent" : [ "COBIT", "HIPAA", "ISO27001", "NIST", "FedRAMP", "PCI_DSS", "BITS", "GAPP" ], "description" : "", "certSubControllers" : [ { "name" : "IS-eCommerceTransactions.1" }, { "name" : "IS-eCommerceTransactions.2" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff5ec" }, "name" : "IS-AuditToolsAccess", "parent" : [ "COBIT", "ISO27001", "NIST", "FedRAMP", "BITS", "GAPP" ], "description" : "", "certSubControllers" : [ { "name" : "IS-AuditToolsAccess.1" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff5ed" }, "name" : "IS-Diagnostic", "parent" : [ "COBIT", "ISO27001", "NIST", "FedRAMP", "PCI_DSS", "BITS" ], "description" : "", "certSubControllers" : [ { "name" : "IS-Diagnostic.1" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff5ee" }, "name" : "IS-Network", "parent" : [ "COBIT", "ISO27001", "NIST", "FedRAMP", "BITS", "GAPP" ], "description" : "", "certSubControllers" : [ { "name" : "IS-Network.1" }, { "name" : "IS-Network.2" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff5ef" }, "name" : "IS-Portable", "parent" : [ "COBIT", "HIPAA", "ISO27001", "NIST", "FedRAMP", "PCI_DSS", "BITS", "GAPP" ], "description" : "", "certSubControllers" : [ { "name" : "IS-Portable.1" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff5f0" }, "name" : "IS-SourceCodeAccessRestriction", "parent" : [ "ISO27001", "NIST", "FedRAMP", "PCI_DSS", "BITS", "GAPP" ], "description" : "", "certSubControllers" : [ { "name" : "IS-SourceCodeAccessRestriction.1" }, { "name" : "IS-SourceCodeAccessRestriction.2" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff5f1" }, "name" : "IS-UtilityProgramsAccess", "parent" : [ "COBIT", "ISO27001", "NIST", "FedRAMP", "PCI_DSS", "BITS" ], "description" : "", "certSubControllers" : [ { "name" : "IS-UtilityProgramsAccess.1" }, { "name" : "IS-UtilityProgramsAccess.2" }, { "name" : "IS-UtilityProgramsAccess.3" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff5f2" }, "name" : "L-Non-DisclosureAgreements", "parent" : [ "COBIT", "ISO27001", "NIST", "FedRAMP", "PCI_DSS", "BITS", "GAPP" ], "description" : "", "certSubControllers" : [ { "name" : "L-Non-DisclosureAgreements.1" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff5f3" }, "name" : "L-ThirdPartyAgreements", "parent" : [ "COBIT", "HIPAA", "ISO27001", "NIST", "FedRAMP", "PCI_DSS", "BITS", "GAPP" ], "description" : "", "certSubControllers" : [ { "name" : "L-ThirdPartyAgreements.1" }, { "name" : "L-ThirdPartyAgreements.2" }, { "name" : "L-ThirdPartyAgreements.3" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff5f4" }, "name" : "OM-Policy", "parent" : [ "COBIT", "ISO27001", "NIST", "FedRAMP", "PCI_DSS", "BITS", "GAPP" ], "description" : "", "certSubControllers" : [ { "name" : "OM-Policy.1" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff5f5" }, "name" : "OM-Documentation", "parent" : [ "COBIT", "ISO27001", "NIST", "FedRAMP", "PCI_DSS", "BITS", "GAPP" ], "description" : "", "certSubControllers" : [ { "name" : "OM-Documentation.1" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff5f6" }, "name" : "OM-Capacity", "parent" : [ "COBIT", "ISO27001", "NIST", "FedRAMP", "BITS", "GAPP" ], "description" : "", "certSubControllers" : [ { "name" : "OM-Capacity.1" }, { "name" : "OM-Capacity.2" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff5f7" }, "name" : "OM-EquipmentMaintenance", "parent" : [ "COBIT", "HIPAA", "ISO27001", "NIST", "FedRAMP", "BITS", "GAPP" ], "description" : "", "certSubControllers" : [ { "name" : "OM-EquipmentMaintenance.1" }, { "name" : "OM-EquipmentMaintenance.2" }, { "name" : "OM-EquipmentMaintenance.3" }, { "name" : "OM-EquipmentMaintenance.4" }, { "name" : "OM-EquipmentMaintenance.5" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff5f8" }, "name" : "RM-Program", "parent" : [ "COBIT", "HIPAA", "ISO27001", "NIST", "FedRAMP", "PCI_DSS", "BITS", "GAPP" ], "description" : "", "certSubControllers" : [ { "name" : "RM-Program.1" }, { "name" : "RM-Program.2" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff5f9" }, "name" : "RM-Assessments", "parent" : [ "COBIT", "HIPAA", "ISO27001", "NIST", "FedRAMP", "PCI_DSS", "BITS", "GAPP" ], "description" : "", "certSubControllers" : [ { "name" : "RM-Assessments.1" }, { "name" : "RM-Assessments.2" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff5fa" }, "name" : "RM-Mitigation", "parent" : [ "COBIT", "HIPAA", "ISO27001", "NIST", "FedRAMP", "BITS" ], "description" : "", "certSubControllers" : [ { "name" : "RM-Mitigation.1" }, { "name" : "RM-Mitigation.2" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff5fb" }, "name" : "RM-Business", "parent" : [ "COBIT", "ISO27001", "NIST", "FedRAMP", "PCI_DSS", "BITS" ], "description" : "", "certSubControllers" : [ { "name" : "RM-Business.1" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff5fc" }, "name" : "RM-ThirdPartyAccess", "parent" : [ "COBIT", "ISO27001", "NIST", "FedRAMP", "PCI_DSS", "BITS", "GAPP" ], "description" : "", "certSubControllers" : [ { "name" : "RM-ThirdPartyAccess.1" }, { "name" : "RM-ThirdPartyAccess.2" }, { "name" : "RM-ThirdPartyAccess.3" }, { "name" : "RM-ThirdPartyAccess.4" }, { "name" : "RM-ThirdPartyAccess.5" }, { "name" : "RM-ThirdPartyAccess.6" }, { "name" : "RM-ThirdPartyAccess.7" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff5fd" }, "name" : "ReM-NewDevelopment", "parent" : [ "COBIT", "ISO27001", "NIST", "FedRAMP", "PCI_DSS", "BITS", "GAPP" ], "description" : "", "certSubControllers" : [ { "name" : "ReM-NewDevelopment.1" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff5fe" }, "name" : "ReM-ProductionChanges", "parent" : [ "COBIT", "HIPAA", "ISO27001", "NIST", "FedRAMP", "PCI_DSS", "BITS", "GAPP" ], "description" : "", "certSubControllers" : [ { "name" : "ReM-ProductionChanges.1" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff5ff" }, "name" : "ReM-QualityTesting", "parent" : [ "COBIT", "ISO27001", "NIST", "FedRAMP", "PCI_DSS", "BITS", "GAPP" ], "description" : "", "certSubControllers" : [ { "name" : "ReM-QualityTesting.1" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff600" }, "name" : "ReM-OutsourcedDevelopment", "parent" : [ "ISO27001", "NIST", "FedRAMP", "PCI_DSS", "BITS" ], "description" : "", "certSubControllers" : [ { "name" : "ReM-OutsourcedDevelopment.1" }, { "name" : "ReM-OutsourcedDevelopment.2" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff601" }, "name" : "ReM-UnauthorizedSoftwareInstallations", "parent" : [ "ISO27001", "NIST", "FedRAMP", "BITS", "GAPP" ], "description" : "", "certSubControllers" : [ { "name" : "ReM-UnauthorizedSoftwareInstallations.1" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff602" }, "name" : "R-ManagementProgram", "parent" : [ "COBIT", "HIPAA", "ISO27001", "NIST", "FedRAMP", "PCI_DSS", "BITS" ], "description" : "", "certSubControllers" : [ { "name" : "R-ManagementProgram.1" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff603" }, "name" : "R-ImpactAnalysis", "parent" : [ "HIPAA", "ISO27001", "NIST", "FedRAMP", "BITS" ], "description" : "", "certSubControllers" : [ { "name" : "R-ImpactAnalysis.1" }, { "name" : "R-ImpactAnalysis.2" }, { "name" : "R-ImpactAnalysis.3" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff604" }, "name" : "R-BusinessContinuityPlanning", "parent" : [ "HIPAA", "ISO27001", "NIST", "FedRAMP", "PCI_DSS", "BITS" ], "description" : "", "certSubControllers" : [ { "name" : "R-BusinessContinuityPlanning.1" }, { "name" : "R-BusinessContinuityPlanning.2" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff605" }, "name" : "R - BusinessContinuityTesting", "parent" : [ "HIPAA", "ISO27001", "NIST", "FedRAMP", "PCI_DSS", "BITS" ], "description" : "", "certSubControllers" : [ { "name" : "R-BusinessContinuityTesting.1" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff606" }, "name" : "R - EnvironmentalRisks", "parent" : [ "HIPAA", "ISO27001", "NIST", "FedRAMP", "BITS", "GAPP" ], "description" : "", "certSubControllers" : [ { "name" : "R-EnvironmentalRisks.1" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff607" }, "name" : "R - EquipmentLocation", "parent" : [ "HIPAA", "ISO27001", "NIST", "FedRAMP", "PCI_DSS", "BITS" ], "description" : "", "certSubControllers" : [ { "name" : "R-EquipmentPowerFailures.1" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff608" }, "name" : "R - EquipmentPowerFailures", "parent" : [ "ISO27001", "NIST", "FedRAMP", "BITS" ], "description" : "", "certSubControllers" : [ { "name" : "R-EquipmentPowerFailures.1" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff609" }, "name" : "R - Power", "parent" : [ "ISO27001", "NIST", "FedRAMP", "BITS" ], "description" : "", "certSubControllers" : [ { "name" : "R-Power.1" }, { "name" : "R-Power.2" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff60a" }, "name" : "SA - CustomerAccessRequirements", "parent" : [ "ISO27001", "NIST", "FedRAMP", "BITS", "GAPP" ], "description" : "", "certSubControllers" : [ { "name" : "SA-CustomerAccessRequirements.1" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff60b" }, "name" : "SA - UserIDCredentials", "parent" : [ "COBIT", "HIPAA", "ISO27001", "NIST", "FedRAMP", "PCI_DSS", "BITS" ], "description" : "", "certSubControllers" : [ { "name" : "SA-UserIDCredentials.1" }, { "name" : "SA-UserIDCredentials.2" }, { "name" : "SA-UserIDCredentials.3" }, { "name" : "SA-UserIDCredentials.4" }, { "name" : "SA-UserIDCredentials.5" }, { "name" : "SA-UserIDCredentials.6" }, { "name" : "SA-UserIDCredentials.7" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff60c" }, "name" : "SA - DataSecurity / Integrity", "parent" : [ "COBIT", "ISO27001", "NIST", "FedRAMP", "PCI_DSS", "BITS", "GAPP" ], "description" : "", "certSubControllers" : [ { "name" : "SA-DataSecurity/Integrity.1" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff60d" }, "name" : "SA - ApplicationSecurity", "parent" : [ "COBIT", "HIPAA", "ISO27001", "NIST", "FedRAMP", "PCI_DSS", "BITS", "GAPP" ], "description" : "", "certSubControllers" : [ { "name" : "SA-ApplicationSecurity.1" }, { "name" : "SA-ApplicationSecurity.2" }, { "name" : "SA-ApplicationSecurity.3" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff60e" }, "name" : "SA - DataIntegrity", "parent" : [ "HIPAA", "ISO27001", "NIST", "FedRAMP", "PCI_DSS", "BITS", "GAPP" ], "description" : "", "certSubControllers" : [ { "name" : "SA-DataIntegrity.1" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff60f" }, "name" : "SA - Production", "parent" : [ "COBIT", "ISO27001", "NIST", "FedRAMP", "PCI_DSS", "BITS", "GAPP" ], "description" : "", "certSubControllers" : [ { "name" : "SA-Production.1" }, { "name" : "SA-Production.2" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff610" }, "name" : "SA - RemoteUserMulti", "parent" : [ "ISO27001", "NIST", "FedRAMP", "PCI_DSS", "BITS", "GAPP" ], "description" : "", "certSubControllers" : [ { "name" : "SA-RemoteUserMulti.1" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff611" }, "name" : "SA - NetworkSecurity", "parent" : [ "ISO27001", "NIST", "FedRAMP", "PCI_DSS", "BITS", "GAPP" ], "description" : "", "certSubControllers" : [ { "name" : "SA-NetworkSecurity.1" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff612" }, "name" : "SA - Segmentation", "parent" : [ "COBIT", "HIPAA", "ISO27001", "NIST", "FedRAMP", "PCI_DSS", "BITS" ], "description" : "", "certSubControllers" : [ { "name" : "SA-Segmentation.1" }, { "name" : "SA-Segmentation.2" }, { "name" : "SA-Segmentation.3" }, { "name" : "SA-Segmentation.4" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff613" }, "name" : "SA - WirelessSecurity", "parent" : [ "COBIT", "HIPAA", "ISO27001", "NIST", "FedRAMP", "PCI_DSS", "BITS", "GAPP" ], "description" : "", "certSubControllers" : [ { "name" : "SA-WirelessSecurity.1" }, { "name" : "SA-WirelessSecurity.2" }, { "name" : "SA-WirelessSecurity.3" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff614" }, "name" : "SA - SharedNetworks", "parent" : [ "HIPAA", "ISO27001", "NIST", "FedRAMP", "PCI_DSS", "BITS", "GAPP" ], "description" : "", "certSubControllers" : [ { "name" : "SA-SharedNetworks.1" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff615" }, "name" : "SA - ClockSynchronization", "parent" : [ "COBIT", "ISO27001", "NIST", "FedRAMP", "PCI_DSS", "BITS" ], "description" : "", "certSubControllers" : [ { "name" : "SA-ClockSynchronization.1" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff616" }, "name" : "SA - EquipmentIdentification", "parent" : [ "COBIT", "ISO27001", "NIST", "FedRAMP", "BITS" ], "description" : "", "certSubControllers" : [ { "name" : "SA-EquipmentIdentification.1" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff617" }, "name" : "SA - AuditLogging / IntrusionDetection", "parent" : [ "COBIT", "HIPAA", "ISO27001", "NIST", "FedRAMP", "PCI_DSS", "BITS", "GAPP" ], "description" : "", "certSubControllers" : [ { "name" : "SA-AuditLogging/IntrusionDetection.1" }, { "name" : "SA-AuditLogging/IntrusionDetection.2" }, { "name" : "SA-AuditLogging/IntrusionDetection.3" } ] }
    ,{ "_id" : { "$oid" : "55647cd1ab74fc30966ff618" }, "name" : "SA - MobileCode", "parent" : [ "ISO27001", "NIST", "FedRAMP", "BITS" ], "description" : "", "certSubControllers" : [ { "name" : "SA-MobileCode.1" }, { "name" : "SA-MobileCode.2" } ] }

  ]
}
